name: Deploy to GitHub Pages wth creds

on:
  push:
    branches:
      - main  # ou la branche que tu utilises pour le déploiement

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up environment variables
        run: |
          echo "FIREBASE_APIKEY=${{ secrets.FIREBASE_APIKEY }}" >> $GITHUB_ENV
          echo "FIREBASE_AUTHDOMAIN=${{ secrets.FIREBASE_AUTHDOMAIN }}" >> $GITHUB_ENV
          echo "FIREBASE_DATABASEURL=${{ secrets.FIREBASE_DATABASEURL }}" >> $GITHUB_ENV
          echo "FIREBASE_PROJECTID=${{ secrets.FIREBASE_PROJECTID }}" >> $GITHUB_ENV
          echo "FIREBASE_STORAGEBUCKET=${{ secrets.FIREBASE_STORAGEBUCKET }}" >> $GITHUB_ENV
          echo "FIREBASE_MESSAGINGSENDERID=${{ secrets.FIREBASE_MESSAGINGSENDERID }}" >> $GITHUB_ENV
          echo "FIREBASE_APPID=${{ secrets.FIREBASE_APPID }}" >> $GITHUB_ENV

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: /root  # Spécifie le dossier du site statique
